config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'top/index'

  #イベント投稿
  # get 'imageposts/index'
  # get 'imageposts/top'
  # get "imageposts/index" => "imageposts#index"

  get "imagepost∏s/new" => "imageposts#new"
  get "imageposts/:id" => "imageposts#show"
  post "imageposts/create" => "imageposts#create"

  resources :pictures
  root 'top#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imageposts_controller.rb
class ImagepostsController < ApplicationController
def index
    @imageposts =Picture.all.order(created_at: :desc)
end

def show
    @imagepost = Picture.find_by(id: params[:id])
    puts @imagepost.inspect
end

def new
    @imagepost = Picture.new
end

def create
    Picture.create!(post_params)
    redirect_to("/imageposts/index")
end

def edit
    @imageposts = Picture.find_by(id: params[:id])
end

def update
end

def destroy
end

private
def post_params

end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

    def index
        @picture = Picture.all.order(created_at: :desc)
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    @pictures = Picture.page(params[:page]).per(5)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imageposts_helper.rb
module ImagepostsHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/imageposts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <h1>ImageLists</h1>
    <% @imageposts.each do |imagepost| %>
      <div class="posts-index-item">
        <%= link_to(imagepost.title, "/imageposts/#{imagepost.id}") %>
      </div>
    <% end %>
  </div>
</div>

app/views/imageposts/new.html.erb
<div class="imageposts-main" style="text-align: center;">
    <div class="posts-menu">
        <table>
        <%= form_with model: @imageposts, url:{action: :create} do |f| %>
            <ul class="posts-menu-ul">
                <li class="posts-menu-li">
                a
                </li>
                <li class="posts-menu-li">
                b
                </li>
                <li class="posts-menu-li">
                c
                </li>
            </ul>
            <ul class="posts-menu-ul">
            <%= f.label :title, "title" %>
            <%= f.text_field :title %>
            </ul>
            <ul class="posts-menu-ul">
            <%= f.label :description, "desc"%>
            <%= f.text_field :description %>
            </ul>
            <% end %>
        </table>
    </div>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <table>
      <td style="height: 50px; vertical-align: top; text-align: left;">
          <tr colspan="3" class="tbdtl1" style="border: none;">
          <p>footer</p>
          </tr>
      </td>
  </table>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top <!--navbar-inverse-->">
  <div id="header_wrap" class="header_absolute">
  <!--<a class="logo_text" href="/top/index" style="font-size: 30px;">Tkm.</a>-->
    <a class="logo-image" href="/top/index">
      <img style="height: 40px;" src="/assets/tkm-logo-2.png">
    </a>

    <script>
      var startPos = 0,winScrollTop = 0;
      $(window).on('scroll',function(){
        winScrollTop = $(this).scrollTop();
        if (winScrollTop >= startPos) {
            $('.header_absolute').addClass('transform');
        } else {
            $('.header_absolute').removeClass('transform');
        }
        startPos = winScrollTop;
      });
    </script>

  </div>
</header>
    <div class="top-line">
        <h1 style="font-size: 20px;">\\\\\\\\\</h1>
        <h2 style="font-size: 10px;">----+++++----</h2>
    </div>

app/views/layouts/_sidebar.html.erb
<div class="side-bar-menu fixed-left ">
  <nav>
    <ul>
      <li><%= link_to "2019",   '#' %></li>
        <ul>
            <li><%= link_to "January",   '#' %></li>
            <li><%= link_to "Febrary",   '#' %></li>
            <li><%= link_to "March",   '#' %></li>
            <li><%= link_to "April",   '#' %></li>
            <li><%= link_to "May",   '#' %></li>
            <li><%= link_to "June",   '#' %></li>
        </ul>
      <li><%= link_to "2018", '#' %></li>
        <ul>
            <li><%= link_to "January",   '#' %></li>
            <li><%= link_to "Febrary",   '#' %></li>
            <li><%= link_to "March",   '#' %></li>
            <li><%= link_to "April",   '#' %></li>
            <li><%= link_to "May",   '#' %></li>
            <li><%= link_to "June",   '#' %></li>
        </ul>
      <li><a href="#">INSTAGRAM</a></li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

  <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.0.0/velocity.min.js"></script>
  
  <script>
    // var DIR = "https://localhost:3000/";
    var pc_width = 1080;
    var device = (screen.width < 600 ? 'sp' : 'pc');
    var view_mode = (device == 'pc' || document.cookie.indexOf('view_mode=pc') != -1 ? 'pc' : 'sp');
    if (device == 'sp' && view_mode == 'pc') {
        document.getElementsByName('viewport')[0].setAttribute('content', 'width=' + pc_width + ',initial-scale=1');
    }

    $(function () {
        if (device == 'sp') {
            if (view_mode == 'pc') {
                $('.sp-mode').on('click', function () {
                    var date = new Date();
                    date.setTime(0);
                    document.cookie = 'view_mode=;expires='+date.toGMTString();
                    // document.write('<link rel="stylesheet" href="' + DIR + 'assets/sp.css.scss" type="text/css" />');
                    location.reload(false);
                  
                }).show();
            } else {
                $('.pc-mode').on('click', function () {
                    document.cookie = 'view_mode=pc';
                    // document.write('<link rel="stylesheet" href="' + DIR + 'assets/sp.css.scss" type="text/css" />');
                    location.reload(false);
                    
                }).show();
            }
        }
    });
  </script>
  
    
 <link href="https://fonts.googleapis.com/earlyaccess/sawarabimincho.css" rel="stylesheet">
 
 <%= yield :head %> 

  <title>PictureBox</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" type="text/css" href="assets/pc.css.scss" >
  <link rel="stylesheet" type="text/css" href="assets/sp.css.scss" media="only screen and (max-width:450px)">  

  </head>

  <body id="body-all">
    <%# <%= render 'layouts/header'  %> 

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

        <div id="main">
          <%= yield %>
        </div>

      <%# <%= render 'layouts/footer' %> 
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/picture/edit.html.erb
<% provide(:title, 'Picture-List') %>
<h1>All pictures</h1>

<ul class="">
	<% @pictures.each do |picture| %>
	<li>
		<%= link_to picture.title, picture_path(picture) %>
		<%= picture.description %>
	</li>
	<% end %>

<%= paginate @pictures %>

app/views/picture/index.html.erb
<% provide(:title, 'All Pictures') %>
<h1>All pictures</h1>

<ul class="users">
	<% @pictures.each do |picture| %>
	<li>
		<%= link_to picture.title, picture_path(picture) %>
		<%= picture.description %>
	</li>
	<% end %>

app/views/top/index.html.erb
<% content_for :head do %>
    <style>
            /* .header {
                display: none;
            } */
    </style>
<% end %>

<body >
<div >
    <aside id="side-bar-left">
        <div id="side-bar-left-menu">
            <ul>
                <li class="collection"><a href="#">COLLECTION</a>
                    <ul class="collection-list">
                            <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 10</a></li>
                            <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 9</a></li>
                            <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 8</a></li>
                            <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 7</a></li>
                            <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 6</a></li>
                    </ul>
                </li>
                <li class="_block"><a href="#" class="nav_collection">THE STORY</a>
                    <ul class="collection-submenu"></ul>
                </li>
                <li class="_block"><a href="#" class="nav_collection">SHOP</a>
                    <ul class="collection-submenu"></ul>
                </li>
                <li class="_block"><a href="#" class="nav_collection">CONTACT</a>
                    <ul class="collection-submenu"></ul>
                </li>
                <li class="_block">
                    <%# <button class="sp-mode" style="display:none;">スマートフォン用で表示</button> %>
                </li>
            </ul>
        </div>
    </aside>
</div>

<div class="main">
 <p> frame2</p> 
    main
    <div id="main_img">
        <img src="/assets/sample.jpg">
    </div>
    <div class="box1">
        <div class="list-group">
            <table>
                <thead>
                    <tr>
                        <div style="color: #000; font-size: 30px;">
                        <%# <%= @date + 'のイベント'%> 
                        </div>
                        <br>
                    </tr>
                </thead>
                <tbody id="tbody-frame">
                    <% picture_new = @pictures %> 
                    <% picture_new.first(1).each do |picture| %>
                    <div> 
                        <%= "title : " + picture.title %>
                        <br>
                        <%= "description : " + picture.description %>
                    </div>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<aside id="side-bar-right">
        <p>frame3</p>
</aside>
<script>
    (function($) {
        $(function () {
            $('.collection > a').on('click', function (e) {
                e.preventDefault();
                var $subNav = $(this).next('.collection-list');
                if ($subNav.css("display") === "block") {
                    $(this).addClass('is-active');
                    $subNav.velocity('slideUp', {duration: 400});
                } else {
                    $(this).removeClass('is-active');
                    $subNav.velocity('slideDown', {duration: 400});
                }
            });
        });
    })(jQuery);
</script>

<header class="header">
    <nav class="global-nav">
        <ul class="global-nav__list">
            <!--front--> 
            <label for="menuOn">
                <li class="global-nav__item"><a class="nav_collection"　for="toggle1">COLLECTION</a>
                    <input id="menuOn" type="checkbox">
                    <!--back-->
                    <menu>
                    <ul id ="collection-list" class="collection-list">
                        <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 10</a></li>
                        <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 9</a></li>
                        <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 8</a></li>
                        <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 7</a></li>
                        <li class="collection-list-block"><a href="#" class="collection-list-block-tag">2019 6</a></li>
                    </ul>
                    </menu>
                    <%# <ul class="overlay"></ul> %>
                </li>
            </label>
                <li class="global-nav__item"><a href="#" class="nav_collection">THE STORY</a>
                    <ul class="collection-submenu"></ul>
                </li>
                <li class="global-nav__item"><a href="#" class="nav_collection">SHOP</a>
                    <ul class="collection-submenu"></ul>
                </li>
                <li class="global-nav__item"><a href="#" class="nav_collection">CONTACT</a>
                    <ul class="collection-submenu"></ul>
                </li>
                <li class="global-nav__item">
                    <%# <button class="pc-mode" style="display:none;">PC用で表示</button> %>
                </li>
        </ul>
    </nav>
    <div class="hamburger" id="js-hamburger">
        <span class="hamburger__line hamburger__line--1"></span>
        <span class="hamburger__line hamburger__line--2"></span>
        <span class="hamburger__line hamburger__line--3"></span>
    </div>
    <div class="black-bg" id="js-black-bg"></div>
</header>

<script>
    function toggleNav() {
    var body = document.body;
    var hamburger = document.getElementById('js-hamburger');
    var blackBg = document.getElementById('js-black-bg');

    hamburger.addEventListener('click', function() {
        body.classList.toggle('nav-open');
    });
    blackBg.addEventListener('click', function() {
        body.classList.remove('nav-open');
    });
    }
    toggleNav();
</script>


</body>